### ISSUE TITLE
New build errors on V 14

### ISSUE THREAD

**Issue by mjzuppe** [metaplex-foundation/js#237]
Hi there! I upgraded metaplex/js from 13.2 to 14.1 and now have dozens of errors when building (see below for examples). Is there new types or a a dependency?

FYI: I did clear node_modules and yarn.lock prior to rebuilding
```
node_modules/@metaplex-foundation/js/dist/types/plugins/nftModule/NftBuildersClient.d.ts:2:10 - error TS2724: '"./approveNftCollectionAuthority"' has no exported member named '_approveNftCollectionAuthorityBuildersClient'. Did you mean 'ApproveNftCollectionAuthorityBuilderParams'?

2 import { _approveNftCollectionAuthorityBuildersClient } from './approveNftCollectionAuthority';
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/@metaplex-foundation/js/dist/types/plugins/nftModule/NftBuildersClient.d.ts:3:10 - error TS2724: '"./approveNftUseAuthority"' has no exported member named '_approveNftUseAuthorityBuildersClient'. Did you mean 'ApproveNftUseAuthorityBuilderParams'?

3 import { _approveNftUseAuthorityBuildersClient } from './approveNftUseAuthority';
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/@metaplex-foundation/js/dist/types/plugins/nftModule/NftBuildersClient.d.ts:4:10 - error TS2724: '"./createNft"' has no exported member named '_createNftBuildersClient'. Did you mean 'CreateNftBuilderContext'?

4 import { _createNftBuildersClient } from './createNft';
           ~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/@metaplex-foundation/js/dist/types/plugins/nftModule/NftBuildersClient.d.ts:5:10 - error TS2724: '"./createSft"' has no exported member named '_createSftBuildersClient'. Did you mean 'CreateSftBuilderContext'?

5 import { _createSftBuildersClient } from './createSft';
           ~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/@metaplex-foundation/js/dist/types/plugins/nftModule/NftBuildersClient.d.ts:6:10 - error TS2305: Module '"./deleteNft"' has no exported member '_deleteNftBuildersClient'.

6 import { _deleteNftBuildersClient } from './deleteNft';
           ~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/@metaplex-foundation/js/dist/types/plugins/nftModule/NftBuildersClient.d.ts:7:10 - error TS2724: '"./freezeDelegatedNft"' has no exported member named '_freezeDelegatedNftBuildersClient'. Did you mean 'FreezeDelegatedNftBuilderParams'?

7 import { _freezeDelegatedNftBuildersClient } from './freezeDelegatedNft';
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/@metaplex-foundation/js/dist/types/plugins/nftModule/NftBuildersClient.d.ts:8:10 - error TS2724: '"./migrateToSizedCollectionNft"' has no exported member named '_migrateToSizedCollectionNftBuildersClient'. Did you mean 'MigrateToSizedCollectionNftBuilderParams'?

8 import { _migrateToSizedCollectionNftBuildersClient } from './migrateToSizedCollectionNft';
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/@metaplex-foundation/js/dist/types/plugins/nftModule/NftBuildersClient.d.ts:9:10 - error TS2724: '"./printNewEdition"' has no exported member named '_printNewEditionBuildersClient'. Did you mean 'PrintNewEditionBuilderContext'?

9 import { _printNewEditionBuildersClient } from './printNewEdition';
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/@metaplex-foundation/js/dist/types/plugins/nftModule/NftBuildersClient.d.ts:10:10 - error TS2724: '"./revokeNftCollectionAuthority"' has no exported member named '_revokeNftCollectionAuthorityBuildersClient'. Did you mean 'RevokeNftCollectionAuthorityBuilderParams'?

10 import { _revokeNftCollectionAuthorityBuildersClient } from './revokeNftCollectionAuthority';
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/@metaplex-foundation/js/dist/types/plugins/nftModule/NftBuildersClient.d.ts:11:10 - error TS2724: '"./revokeNftUseAuthority"' has no exported member named '_revokeNftUseAuthorityBuildersClient'. Did you mean 'RevokeNftUseAuthorityBuilderParams'?

11 import { _revokeNftUseAuthorityBuildersClient } from './revokeNftUseAuthority';
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/@metaplex-foundation/js/dist/types/plugins/nftModule/NftBuildersClient.d.ts:12:10 - error TS2724: '"./thawDelegatedNft"' has no exported member named '_thawDelegatedNftBuildersClient'. Did you mean 'ThawDelegatedNftBuilderParams'?

12 import { _thawDelegatedNftBuildersClient } from './thawDelegatedNft';
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/@metaplex-foundation/js/dist/types/plugins/nftModule/NftBuildersClient.d.ts:13:10 - error TS2724: '"./unverifyNftCollection"' has no exported member named '_unverifyNftCollectionBuildersClient'. Did you mean 'UnverifyNftCollectionBuilderParams'?

13 import { _unverifyNftCollectionBuildersClient } from './unverifyNftCollection';
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/@metaplex-foundation/js/dist/types/plugins/nftModule/NftBuildersClient.d.ts:14:10 - error TS2724: '"./unverifyNftCreator"' has no exported member named '_unverifyNftCreatorBuildersClient'. Did you mean 'UnverifyNftCreatorBuilderParams'?

14 import { _unverifyNftCreatorBuildersClient } from './unverifyNftCreator';
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/@metaplex-foundation/js/dist/types/plugins/nftModule/NftBuildersClient.d.ts:15:10 - error TS2305: Module '"./updateNft"' has no exported member '_updateNftBuildersClient'.

15 import { _updateNftBuildersClient } from './updateNft';
            ~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/@metaplex-foundation/js/dist/types/plugins/nftModule/NftBuildersClient.d.ts:16:10 - error TS2305: Module '"./useNft"' has no exported member '_useNftBuildersClient'.

16 import { _useNftBuildersClient } from './useNft';
            ~~~~~~~~~~~~~~~~~~~~~

node_modules/@metaplex-foundation/js/dist/types/plugins/nftModule/NftBuildersClient.d.ts:17:10 - error TS2724: '"./verifyNftCollection"' has no exported member named '_verifyNftCollectionBuildersClient'. Did you mean 'VerifyNftCollectionBuilderParams'?

17 import { _verifyNftCollectionBuildersClient } from './verifyNftCollection';
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/@metaplex-foundation/js/dist/types/plugins/nftModule/NftBuildersClient.d.ts:18:10 - error TS2724: '"./verifyNftCreator"' has no exported member named '_verifyNftCreatorBuildersClient'. Did you mean 'VerifyNftCreatorBuilderParams'?

18 import { _verifyNftCreatorBuildersClient } from './verifyNftCreator';
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/@metaplex-foundation/js/dist/types/plugins/nftModule/NftClient.d.ts:3:10 - error TS2724: '"./approveNftCollectionAuthority"' has no exported member named '_approveNftCollectionAuthorityClient'. Did you mean 'ApproveNftCollectionAuthorityInput'?

3 import { _approveNftCollectionAuthorityClient } from './approveNftCollectionAuthority';
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/@metaplex-foundation/js/dist/types/plugins/nftModule/NftClient.d.ts:4:10 - error TS2724: '"./approveNftUseAuthority"' has no exported member named '_approveNftUseAuthorityClient'. Did you mean 'ApproveNftUseAuthorityInput'?

4 import { _approveNftUseAuthorityClient } from './approveNftUseAuthority';
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/@metaplex-foundation/js/dist/types/plugins/nftModule/NftClient.d.ts:5:10 - error TS2724: '"./createNft"' has no exported member named '_createNftClient'. Did you mean 'CreateNftInput'?

5 import { _createNftClient } from './createNft';
           ~~~~~~~~~~~~~~~~

node_modules/@metaplex-foundation/js/dist/types/plugins/nftModule/NftClient.d.ts:6:10 - error TS2724: '"./createSft"' has no exported member named '_createSftClient'. Did you mean 'CreateSftInput'?

6 import { _createSftClient } from './createSft';
           ~~~~~~~~~~~~~~~~

node_modules/@metaplex-foundation/js/dist/types/plugins/nftModule/NftClient.d.ts:7:10 - error TS2724: '"./deleteNft"' has no exported member named '_deleteNftClient'. Did you mean 'DeleteNftInput'?

7 import { _deleteNftClient } from './deleteNft';
           ~~~~~~~~~~~~~~~~

node_modules/@metaplex-foundation/js/dist/types/plugins/nftModule/NftClient.d.ts:8:10 - error TS2724: '"./findNftByMetadata"' has no exported member named '_findNftByMetadataClient'. Did you mean 'FindNftByMetadataInput'?

8 import { _findNftByMetadataClient } from './findNftByMetadata';
           ~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/@metaplex-foundation/js/dist/types/plugins/nftModule/NftClient.d.ts:9:10 - error TS2724: '"./findNftByMint"' has no exported member named '_findNftByMintClient'. Did you mean 'FindNftByMintInput'?

9 import { _findNftByMintClient, _refreshNftClient } from './findNftByMint';
           ~~~~~~~~~~~~~~~~~~~~

node_modules/@metaplex-foundation/js/dist/types/plugins/nftModule/NftClient.d.ts:9:32 - error TS2305: Module '"./findNftByMint"' has no exported member '_refreshNftClient'.

9 import { _findNftByMintClient, _refreshNftClient } from './findNftByMint';
                                 ~~~~~~~~~~~~~~~~~

node_modules/@metaplex-foundation/js/dist/types/plugins/nftModule/NftClient.d.ts:10:10 - error TS2724: '"./findNftByToken"' has no exported member named '_findNftByTokenClient'. Did you mean 'FindNftByTokenInput'?

10 import { _findNftByTokenClient } from './findNftByToken';
            ~~~~~~~~~~~~~~~~~~~~~

node_modules/@metaplex-foundation/js/dist/types/plugins/nftModule/NftClient.d.ts:11:10 - error TS2305: Module '"./findNftsByCreator"' has no exported member '_findNftsByCreatorsClient'.

11 import { _findNftsByCreatorsClient } from './findNftsByCreator';
            ~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/@metaplex-foundation/js/dist/types/plugins/nftModule/NftClient.d.ts:12:10 - error TS2724: '"./findNftsByMintList"' has no exported member named '_findNftsByMintListClient'. Did you mean 'FindNftsByMintListInput'?

12 import { _findNftsByMintListClient } from './findNftsByMintList';
            ~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/@metaplex-foundation/js/dist/types/plugins/nftModule/NftClient.d.ts:13:10 - error TS2724: '"./findNftsByOwner"' has no exported member named '_findNftsByOwnerClient'. Did you mean 'FindNftsByOwnerInput'?

13 import { _findNftsByOwnerClient } from './findNftsByOwner';
            ~~~~~~~~~~~~~~~~~~~~~~

node_modules/@metaplex-foundation/js/dist/types/plugins/nftModule/NftClient.d.ts:14:10 - error TS2724: '"./findNftsByUpdateAuthority"' has no exported member named '_findNftsByUpdateAuthorityClient'. Did you mean 'FindNftsByUpdateAuthorityInput'?

14 import { _findNftsByUpdateAuthorityClient } from './findNftsByUpdateAuthority';
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/@metaplex-foundation/js/dist/types/plugins/nftModule/NftClient.d.ts:15:10 - error TS2724: '"./freezeDelegatedNft"' has no exported member named '_freezeDelegatedNftClient'. Did you mean 'FreezeDelegatedNftInput'?

15 import { _freezeDelegatedNftClient } from './freezeDelegatedNft';
            ~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/@metaplex-foundation/js/dist/types/plugins/nftModule/NftClient.d.ts:17:10 - error TS2724: '"./loadMetadata"' has no exported member named '_loadMetadataClient'. Did you mean 'LoadMetadataInput'?

17 import { _loadMetadataClient } from './loadMetadata';
            ~~~~~~~~~~~~~~~~~~~

node_modules/@metaplex-foundation/js/dist/types/plugins/nftModule/NftClient.d.ts:18:10 - error TS2724: '"./migrateToSizedCollectionNft"' has no exported member named '_migrateToSizedCollectionNftClient'. Did you mean 'MigrateToSizedCollectionNftInput'?

18 import { _migrateToSizedCollectionNftClient } from './migrateToSizedCollectionNft';
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/@metaplex-foundation/js/dist/types/plugins/nftModule/NftClient.d.ts:20:10 - error TS2724: '"./printNewEdition"' has no exported member named '_printNewEditionClient'. Did you mean 'PrintNewEditionInput'?

20 import { _printNewEditionClient } from './printNewEdition';
            ~~~~~~~~~~~~~~~~~~~~~~

node_modules/@metaplex-foundation/js/dist/types/plugins/nftModule/NftClient.d.ts:21:10 - error TS2724: '"./revokeNftCollectionAuthority"' has no exported member named '_revokeNftCollectionAuthorityClient'. Did you mean 'RevokeNftCollectionAuthorityInput'?

21 import { _revokeNftCollectionAuthorityClient } from './revokeNftCollectionAuthority';
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/@metaplex-foundation/js/dist/types/plugins/nftModule/NftClient.d.ts:22:10 - error TS2724: '"./revokeNftUseAuthority"' has no exported member named '_revokeNftUseAuthorityClient'. Did you mean 'RevokeNftUseAuthorityInput'?

22 import { _revokeNftUseAuthorityClient } from './revokeNftUseAuthority';
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/@metaplex-foundation/js/dist/types/plugins/nftModule/NftClient.d.ts:23:10 - error TS2724: '"./thawDelegatedNft"' has no exported member named '_thawDelegatedNftClient'. Did you mean 'ThawDelegatedNftInput'?

23 import { _thawDelegatedNftClient } from './thawDelegatedNft';
            ~~~~~~~~~~~~~~~~~~~~~~~

node_modules/@metaplex-foundation/js/dist/types/plugins/nftModule/NftClient.d.ts:24:10 - error TS2724: '"./unverifyNftCollection"' has no exported member named '_unverifyNftCollectionClient'. Did you mean 'UnverifyNftCollectionInput'?

24 import { _unverifyNftCollectionClient } from './unverifyNftCollection';
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/@metaplex-foundation/js/dist/types/plugins/nftModule/NftClient.d.ts:25:10 - error TS2724: '"./unverifyNftCreator"' has no exported member named '_unverifyNftCreatorClient'. Did you mean 'UnverifyNftCreatorInput'?

25 import { _unverifyNftCreatorClient } from './unverifyNftCreator';
            ~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/@metaplex-foundation/js/dist/types/plugins/nftModule/NftClient.d.ts:26:10 - error TS2724: '"./updateNft"' has no exported member named '_updateNftClient'. Did you mean 'UpdateNftInput'?

26 import { _updateNftClient } from './updateNft';
            ~~~~~~~~~~~~~~~~

node_modules/@metaplex-foundation/js/dist/types/plugins/nftModule/NftClient.d.ts:27:10 - error TS2724: '"./uploadMetadata"' has no exported member named '_uploadMetadataClient'. Did you mean 'UploadMetadataInput'?

27 import { _uploadMetadataClient } from './uploadMetadata';
            ~~~~~~~~~~~~~~~~~~~~~

node_modules/@metaplex-foundation/js/dist/types/plugins/nftModule/NftClient.d.ts:28:10 - error TS2305: Module '"./useNft"' has no exported member '_useNftClient'.

28 import { _useNftClient } from './useNft';
            ~~~~~~~~~~~~~

node_modules/@metaplex-foundation/js/dist/types/plugins/nftModule/NftClient.d.ts:29:10 - error TS2724: '"./verifyNftCollection"' has no exported member named '_verifyNftCollectionClient'. Did you mean 'VerifyNftCollectionInput'?

29 import { _verifyNftCollectionClient } from './verifyNftCollection';
            ~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/@metaplex-foundation/js/dist/types/plugins/nftModule/NftClient.d.ts:30:10 - error TS2724: '"./verifyNftCreator"' has no exported member named '_verifyNftCreatorClient'. Did you mean 'VerifyNftCreatorInput'?

30 import { _verifyNftCreatorClient } from './verifyNftCreator';
            ~~~~~~~~~~~~~~~~~~~~~~~

node_modules/@metaplex-foundation/js/dist/types/plugins/tokenModule/TokenBuildersClient.d.ts:2:10 - error TS2724: '"./approveTokenDelegateAuthority"' has no exported member named '_approveTokenDelegateAuthorityBuildersClient'. Did you mean 'ApproveTokenDelegateAuthorityBuilderParams'?

2 import { _approveTokenDelegateAuthorityBuildersClient } from './approveTokenDelegateAuthority';
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/@metaplex-foundation/js/dist/types/plugins/tokenModule/TokenBuildersClient.d.ts:3:10 - error TS2724: '"./createMint"' has no exported member named '_createMintBuildersClient'. Did you mean 'CreateMintBuilderContext'?

3 import { _createMintBuildersClient } from './createMint';
           ~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/@metaplex-foundation/js/dist/types/plugins/tokenModule/TokenBuildersClient.d.ts:4:10 - error TS2724: '"./createToken"' has no exported member named '_createTokenBuildersClient'. Did you mean 'CreateTokenBuilderContext'?

4 import { _createTokenBuildersClient, _createTokenIfMissingBuildersClient } from './createToken';
           ~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/@metaplex-foundation/js/dist/types/plugins/tokenModule/TokenBuildersClient.d.ts:4:38 - error TS2724: '"./createToken"' has no exported member named '_createTokenIfMissingBuildersClient'. Did you mean 'CreateTokenIfMissingBuilderParams'?

4 import { _createTokenBuildersClient, _createTokenIfMissingBuildersClient } from './createToken';
                                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/@metaplex-foundation/js/dist/types/plugins/tokenModule/TokenBuildersClient.d.ts:5:10 - error TS2724: '"./createTokenWithMint"' has no exported member named '_createTokenWithMintBuildersClient'. Did you mean 'CreateTokenWithMintBuilderContext'?

5 import { _createTokenWithMintBuildersClient } from './createTokenWithMint';
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/@metaplex-foundation/js/dist/types/plugins/tokenModule/TokenBuildersClient.d.ts:6:10 - error TS2305: Module '"./freezeTokens"' has no exported member '_freezeTokensBuildersClient'.

6 import { _freezeTokensBuildersClient } from './freezeTokens';
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/@metaplex-foundation/js/dist/types/plugins/tokenModule/TokenBuildersClient.d.ts:7:10 - error TS2305: Module '"./mintTokens"' has no exported member '_mintTokensBuildersClient'.

7 import { _mintTokensBuildersClient } from './mintTokens';
           ~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/@metaplex-foundation/js/dist/types/plugins/tokenModule/TokenBuildersClient.d.ts:8:10 - error TS2724: '"./revokeTokenDelegateAuthority"' has no exported member named '_revokeTokenDelegateAuthorityBuildersClient'. Did you mean 'RevokeTokenDelegateAuthorityBuilderParams'?

8 import { _revokeTokenDelegateAuthorityBuildersClient } from './revokeTokenDelegateAuthority';
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/@metaplex-foundation/js/dist/types/plugins/tokenModule/TokenBuildersClient.d.ts:9:10 - error TS2305: Module '"./sendTokens"' has no exported member '_sendTokensBuildersClient'.

9 import { _sendTokensBuildersClient } from './sendTokens';
           ~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/@metaplex-foundation/js/dist/types/plugins/tokenModule/TokenBuildersClient.d.ts:10:10 - error TS2305: Module '"./thawTokens"' has no exported member '_thawTokensBuildersClient'.

10 import { _thawTokensBuildersClient } from './thawTokens';
            ~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/@metaplex-foundation/js/dist/types/plugins/tokenModule/TokenClient.d.ts:2:10 - error TS2724: '"./approveTokenDelegateAuthority"' has no exported member named '_approveTokenDelegateAuthorityClient'. Did you mean 'ApproveTokenDelegateAuthorityInput'?

2 import { _approveTokenDelegateAuthorityClient } from './approveTokenDelegateAuthority';
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/@metaplex-foundation/js/dist/types/plugins/tokenModule/TokenClient.d.ts:3:10 - error TS2724: '"./createMint"' has no exported member named '_createMintClient'. Did you mean 'CreateMintInput'?

3 import { _createMintClient } from './createMint';
           ~~~~~~~~~~~~~~~~~

node_modules/@metaplex-foundation/js/dist/types/plugins/tokenModule/TokenClient.d.ts:4:10 - error TS2724: '"./createToken"' has no exported member named '_createTokenClient'. Did you mean 'CreateTokenInput'?

4 import { _createTokenClient } from './createToken';
           ~~~~~~~~~~~~~~~~~~

node_modules/@metaplex-foundation/js/dist/types/plugins/tokenModule/TokenClient.d.ts:5:10 - error TS2724: '"./createTokenWithMint"' has no exported member named '_createTokenWithMintClient'. Did you mean 'CreateTokenWithMintInput'?

5 import { _createTokenWithMintClient } from './createTokenWithMint';
           ~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/@metaplex-foundation/js/dist/types/plugins/tokenModule/TokenClient.d.ts:6:10 - error TS2724: '"./findMintByAddress"' has no exported member named '_findMintByAddressClient'. Did you mean 'FindMintByAddressInput'?

6 import { _findMintByAddressClient } from './findMintByAddress';
           ~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/@metaplex-foundation/js/dist/types/plugins/tokenModule/TokenClient.d.ts:7:10 - error TS2724: '"./findTokenByAddress"' has no exported member named '_findTokenByAddressClient'. Did you mean 'FindTokenByAddressInput'?

7 import { _findTokenByAddressClient } from './findTokenByAddress';
           ~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/@metaplex-foundation/js/dist/types/plugins/tokenModule/TokenClient.d.ts:8:10 - error TS2724: '"./findTokenWithMintByAddress"' has no exported member named '_findTokenWithMintByAddressClient'. Did you mean 'FindTokenWithMintByAddressInput'?

8 import { _findTokenWithMintByAddressClient } from './findTokenWithMintByAddress';
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/@metaplex-foundation/js/dist/types/plugins/tokenModule/TokenClient.d.ts:9:10 - error TS2724: '"./findTokenWithMintByMint"' has no exported member named '_findTokenWithMintByMintClient'. Did you mean 'FindTokenWithMintByMintInput'?

9 import { _findTokenWithMintByMintClient } from './findTokenWithMintByMint';
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/@metaplex-foundation/js/dist/types/plugins/tokenModule/TokenClient.d.ts:10:10 - error TS2724: '"./freezeTokens"' has no exported member named '_freezeTokensClient'. Did you mean 'FreezeTokensInput'?

10 import { _freezeTokensClient } from './freezeTokens';
            ~~~~~~~~~~~~~~~~~~~

node_modules/@metaplex-foundation/js/dist/types/plugins/tokenModule/TokenClient.d.ts:11:10 - error TS2724: '"./mintTokens"' has no exported member named '_mintTokensClient'. Did you mean 'MintTokensInput'?

11 import { _mintTokensClient } from './mintTokens';
            ~~~~~~~~~~~~~~~~~

node_modules/@metaplex-foundation/js/dist/types/plugins/tokenModule/TokenClient.d.ts:12:10 - error TS2724: '"./revokeTokenDelegateAuthority"' has no exported member named '_revokeTokenDelegateAuthorityClient'. Did you mean 'RevokeTokenDelegateAuthorityInput'?

12 import { _revokeTokenDelegateAuthorityClient } from './revokeTokenDelegateAuthority';
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/@metaplex-foundation/js/dist/types/plugins/tokenModule/TokenClient.d.ts:13:10 - error TS2724: '"./sendTokens"' has no exported member named '_sendTokensClient'. Did you mean 'SendTokensInput'?

13 import { _sendTokensClient } from './sendTokens';
            ~~~~~~~~~~~~~~~~~

node_modules/@metaplex-foundation/js/dist/types/plugins/tokenModule/TokenClient.d.ts:14:10 - error TS2724: '"./thawTokens"' has no exported member named '_thawTokensClient'. Did you mean 'ThawTokensInput'?

14 import { _thawTokensClient } from './thawTokens';
            ~~~~~~~~~~~~~~~~~

```

**Comment by lorisleiva** [comment]
Hey there 👋 

Yeah, that refactoring was a mistake. It made things easier for us to maintain but caused some TS and IntelliSense issues.

Version 0.15.0 (releasing very soon) will fix that but change the top-level API slightly.

**Comment by lorisleiva** [comment]
This should now be fixed in version [`0.15`](https://github.com/metaplex-foundation/js/releases/tag/js%2Fv0.15.0). 🚀

**Comment by mjzuppe** [comment]
@lorisleiva - Confirm V15 patched those errors. Have new errors that I'm now reviewing:

```
node_modules/@metaplex-foundation/js/dist/types/plugins/tokenModule/program.d.ts:1:10 - error TS2305: Module '"./gpaBuilders"' has no exported member 'MintGpaBuilder'.

1 import { MintGpaBuilder, TokenGpaBuilder } from './gpaBuilders';
           ~~~~~~~~~~~~~~

node_modules/@metaplex-foundation/js/dist/types/plugins/tokenModule/program.d.ts:1:26 - error TS2305: Module '"./gpaBuilders"' has no exported member 'TokenGpaBuilder'.

1 import { MintGpaBuilder, TokenGpaBuilder } from './gpaBuilders';
```

**Comment by lorisleiva** [comment]
Got it, thanks for letting me know.

**Comment by okwasi** [comment]
> es2019

Did you only have to change this @mjzuppe? I had the same missing exports issue as you, but changing the tsconfig target to es2019 didn't solve the issue.

**Comment by okwasi** [comment]
@lorisleiva I see that the version 0.15 in npm specifies the exports in `gpaBuilders.d.ts` as `{}`. And so `program.d.ts` throws errors, as it's unable to import `MintGpaBuilder` and `TokenGpaBuilder`. Any idea how I can get around this?

**Comment by okwasi** [comment]
> > > es2019
> > 
> > 
> > Did you only have to change this @mjzuppe? I had the same missing exports issue as you, but changing the tsconfig target to es2019 didn't solve the issue.
> 
> I don't recall specifically what else I may have changed, but here is my current `tsconfig.json` that's building successfully if that's helpful:
> 
> ```
> {
>   "compilerOptions": {
>     "declaration": true,
>     "module": "CommonJS",
>     "skipLibCheck": true,
>     "target": "es2019",
>     "outDir": "./js",
>     "allowJs": true,
>     "moduleResolution": "node",
>     "allowSyntheticDefaultImports": true
>   },
>   "include": ["./src", "index.ts"]
> }
> ```

Thanks a lot @mjzuppe! So it turns out the tsconfig parameter that fixed it was skipLibCheck! I'm all good now.

**Comment by yuwiggin** [comment]
I had the Same issue when `"skipLibCheck": true, "target": "es2019",`  was set. i.e. `tsconfig.json`:
 ```
{
  "compilerOptions": {
    "types": ["mocha", "chai"],
    "typeRoots": ["./node_modules/@types"],
    "lib": ["es2015"],
    "module": "commonjs",
    "target": "es2019",
    "esModuleInterop": true,    
    "skipLibCheck": true,
    "noImplicitAny": false,
  }
}
``` 
Here is the `package.json`: 
```
{
    "scripts": {
        "lint:fix": "prettier */*.js \"*/**/*{.js,.ts}\" -w",
        "lint": "prettier */*.js \"*/**/*{.js,.ts}\" --check"
    },
    "dependencies": {
        "@metaplex-foundation/js": "^0.15.0",
        "@project-serum/anchor": "^0.25.0",
        "bs58": "^5.0.0"
    },
    "devDependencies": {
        "@types/bn.js": "^5.1.0",
        "@types/chai": "^4.3.0",
        "@types/mocha": "^9.0.0",
        "chai": "^4.3.4",
        "mocha": "^9.0.3",
        "prettier": "^2.6.2",
        "ts-mocha": "^10.0.0",
        "typescript": "^4.3.5"
    }
}
```
Any suggestion?
